[package]
name = "pi-utils"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
frontmatter = ["dep:serde", "dep:serde_yaml"]

[dependencies]
serde = { workspace = true, optional = true }
serde_yaml = { version = "0.9.34", optional = true }
