use std::collections::BTreeMap;

use pi_core::{ModelCost, ModelInput, ModelSpec};

use crate::{GOOGLE_BASE_URL, GOOGLE_GENERATIVE_AI_API, GOOGLE_PROVIDER_ID};

#[derive(Clone, Copy)]
enum ThinkingMap {
    Default,
    NoOff,
    LowHigh,
    Gemma,
}

/// Returns the current Pi Google AI Studio model catalog.
pub fn google_models() -> Vec<ModelSpec> {
    vec![
        model(
            "deep-research-max-preview-04-2026",
            "Deep Research Max Preview (Apr-21-2026)",
            131_072,
            65_536,
            2.0,
            12.0,
            0.2,
            ThinkingMap::Default,
        ),
        model(
            "deep-research-preview-04-2026",
            "Deep Research Preview (Apr-21-2026)",
            131_072,
            65_536,
            2.0,
            12.0,
            0.2,
            ThinkingMap::Default,
        ),
        model(
            "gemini-2.5-computer-use-preview-10-2025",
            "Gemini 2.5 Computer Use Preview 10-2025",
            131_072,
            65_536,
            1.25,
            10.0,
            0.0,
            ThinkingMap::Default,
        ),
        model(
            "gemini-2.5-flash",
            "Gemini 2.5 Flash",
            1_048_576,
            65_536,
            0.3,
            2.5,
            0.03,
            ThinkingMap::Default,
        ),
        model(
            "gemini-2.5-flash-lite",
            "Gemini 2.5 Flash-Lite",
            1_048_576,
            65_536,
            0.1,
            0.4,
            0.01,
            ThinkingMap::Default,
        ),
        model(
            "gemini-2.5-pro",
            "Gemini 2.5 Pro",
            1_048_576,
            65_536,
            1.25,
            10.0,
            0.125,
            ThinkingMap::Default,
        ),
        model(
            "gemini-3-flash-preview",
            "Gemini 3 Flash Preview",
            1_048_576,
            65_536,
            0.5,
            3.0,
            0.05,
            ThinkingMap::NoOff,
        ),
        model(
            "gemini-3.1-flash-lite",
            "Gemini 3.1 Flash Lite",
            1_048_576,
            65_536,
            0.25,
            1.5,
            0.025,
            ThinkingMap::NoOff,
        ),
        model(
            "gemini-3.1-flash-lite-image",
            "Nano Banana 2 Lite",
            65_536,
            65_536,
            0.25,
            30.0,
            0.0,
            ThinkingMap::NoOff,
        ),
        model(
            "gemini-3.1-flash-lite-preview",
            "Gemini 3.1 Flash Lite Preview",
            1_048_576,
            65_536,
            0.25,
            1.5,
            0.025,
            ThinkingMap::NoOff,
        ),
        model(
            "gemini-3.1-flash-live-preview",
            "Gemini 3.1 Flash Live Preview",
            131_072,
            65_536,
            0.75,
            4.5,
            0.0,
            ThinkingMap::NoOff,
        ),
        model(
            "gemini-3.1-pro-preview",
            "Gemini 3.1 Pro Preview",
            1_048_576,
            65_536,
            2.0,
            12.0,
            0.2,
            ThinkingMap::LowHigh,
        ),
        model(
            "gemini-3.1-pro-preview-customtools",
            "Gemini 3.1 Pro Preview Custom Tools",
            1_048_576,
            65_536,
            2.0,
            12.0,
            0.2,
            ThinkingMap::LowHigh,
        ),
        model(
            "gemini-3.5-flash",
            "Gemini 3.5 Flash",
            1_048_576,
            65_536,
            1.5,
            9.0,
            0.15,
            ThinkingMap::NoOff,
        ),
        model(
            "gemini-3.5-flash-lite",
            "Gemini 3.5 Flash Lite",
            1_048_576,
            65_536,
            0.3,
            2.5,
            0.03,
            ThinkingMap::NoOff,
        ),
        model(
            "gemini-3.6-flash",
            "Gemini 3.6 Flash",
            1_048_576,
            65_536,
            1.5,
            7.5,
            0.15,
            ThinkingMap::NoOff,
        ),
        model(
            "gemini-3.7-flash",
            "Gemini 3.7 Flash",
            1_048_576,
            65_536,
            0.75,
            3.75,
            0.075,
            ThinkingMap::NoOff,
        ),
        model(
            "gemini-flash-latest",
            "Gemini Flash Latest",
            1_048_576,
            65_536,
            1.5,
            9.0,
            0.15,
            ThinkingMap::NoOff,
        ),
        model(
            "gemini-flash-lite-latest",
            "Gemini Flash-Lite Latest",
            1_048_576,
            65_536,
            0.25,
            1.5,
            0.025,
            ThinkingMap::NoOff,
        ),
        model(
            "gemini-robotics-er-1.6-preview",
            "Gemini Robotics-ER 1.6 Preview",
            131_072,
            65_536,
            1.0,
            5.0,
            0.0,
            ThinkingMap::Default,
        ),
        model(
            "gemma-4-26b-a4b-it",
            "Gemma 4 26B A4B IT",
            262_144,
            32_768,
            0.0,
            0.0,
            0.0,
            ThinkingMap::Gemma,
        ),
        model(
            "gemma-4-31b-it",
            "Gemma 4 31B IT",
            262_144,
            32_768,
            0.0,
            0.0,
            0.0,
            ThinkingMap::Gemma,
        ),
    ]
}

#[allow(clippy::too_many_arguments)]
fn model(
    id: &str,
    name: &str,
    context_window: u64,
    max_tokens: u64,
    input_cost: f64,
    output_cost: f64,
    cache_read_cost: f64,
    thinking_map: ThinkingMap,
) -> ModelSpec {
    let mut model = ModelSpec::new(GOOGLE_PROVIDER_ID, id, name, GOOGLE_GENERATIVE_AI_API);
    model.base_url = Some(GOOGLE_BASE_URL.to_string());
    model.reasoning = true;
    model.input = vec![ModelInput::Text, ModelInput::Image];
    model.cost = ModelCost {
        input: input_cost,
        output: output_cost,
        cache_read: cache_read_cost,
        cache_write: 0.0,
        tiers: Vec::new(),
    };
    model.context_window = context_window;
    model.max_tokens = max_tokens;
    model.thinking_level_map = match thinking_map {
        ThinkingMap::Default => BTreeMap::new(),
        ThinkingMap::NoOff => BTreeMap::from([("off".to_string(), None)]),
        ThinkingMap::LowHigh => BTreeMap::from([
            ("off".to_string(), None),
            ("minimal".to_string(), None),
            ("low".to_string(), Some("LOW".to_string())),
            ("medium".to_string(), None),
            ("high".to_string(), Some("HIGH".to_string())),
        ]),
        ThinkingMap::Gemma => BTreeMap::from([
            ("off".to_string(), None),
            ("minimal".to_string(), Some("MINIMAL".to_string())),
            ("low".to_string(), None),
            ("medium".to_string(), None),
            ("high".to_string(), Some("HIGH".to_string())),
        ]),
    };
    model
}
