[package]
name = "pi-plugin-azure-openai"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
pi-core.workspace = true
pi-plugin-openai.workspace = true
pi-provider.workspace = true
serde_json.workspace = true

[dev-dependencies]
futures.workspace = true
tokio.workspace = true
