import { describe, expect, it } from "vitest";
import { looksAutoGeneratedThreadName } from "./threadNaming";

describe("looksAutoGeneratedThreadName", () => {
  it.each(["Untitled session", "untitled session", " UNTITLED SESSION "])(
    "treats the desktop placeholder %j as auto-generated",
    (name) => {
      expect(looksAutoGeneratedThreadName(name)).toBe(true);
    },
  );

  it("does not replace a user-defined session title", () => {
    expect(looksAutoGeneratedThreadName("Investigate login latency")).toBe(false);
  });
});
