#![deny(unsafe_op_in_unsafe_fn)]

use std::path::{Path, PathBuf};
#[cfg(any(feature = "agent", feature = "provider", feature = "session"))]
use std::sync::Arc;

pub use async_trait::async_trait;
#[doc(hidden)]
pub use async_trait::async_trait as __plugin_async_trait;
pub use pi_core::PluginId;
pub use pi_plugin_macros::{agent, provider, session};
use schemars::JsonSchema;
use serde::de::DeserializeOwned;
pub use serde_json::Value as PluginOptionsValue;

#[cfg(feature = "provider")]
pub use pi_core::ProviderPlugin;
#[cfg(feature = "agent")]
pub use pi_core::{AgentHook, AgentHookInterests, AgentPlugin};
#[cfg(feature = "session")]
pub use pi_session::plugin::SessionPlugin;

/// Version of the trusted Rust-ABI plugin contract.
///
/// ABI 15 replaces core tool-run state with a run identity and explicit
/// invocation-private Agent plugins for ephemeral Agents.
/// ABI 14 adds detached context compaction, transient execution provenance,
/// and typed invocation-local tool state. ABI 13 adds inherited fork prompts/history, invocation-local observations,
/// guarded dispatch, and input budgets. ABI 12 adds bounded ephemeral sessions to the generation-bound session
/// capability. ABI 11 adds tool-free direct completion to the generation-bound session
/// capability. ABI 10 adds inherited model, thinking, and active-tool selection for fresh
/// isolated sessions. ABI 9 added independently running sessions to the
/// generation-bound session context. ABI 8 added asynchronous semantic
/// confirmation to the UI context.
/// ABI 7 replaced cumulative message-update snapshots with a shared live stream
/// handle plus one compact [`pi_core::StreamEvent`] delta. ABI 6 shared immutable
/// cumulative partials; ABI 5 added the generation-bound Pi product context and
/// tool argument preparation.
/// Hosts must reject older artifacts before resolving their Rust-ABI
/// constructors.
pub const NATIVE_PLUGIN_ABI_VERSION: u32 = 15;
pub const BUILD_FINGERPRINT: &str = env!("PI_PLUGIN_BUILD_FINGERPRINT");

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u32)]
pub enum NativePluginKind {
    Agent = 1,
    Provider = 2,
    Session = 3,
}

impl NativePluginKind {
    pub fn from_u32(value: u32) -> Option<Self> {
        match value {
            1 => Some(Self::Agent),
            2 => Some(Self::Provider),
            3 => Some(Self::Session),
            _ => None,
        }
    }
}

#[derive(Clone, Copy)]
#[repr(C)]
pub struct NativeBytes {
    pub ptr: *const u8,
    pub len: usize,
}

// SAFETY: `NativeBytes` values in plugin descriptors only point at immutable
// static byte strings generated by the export macros.
unsafe impl Send for NativeBytes {}
// SAFETY: See the `Send` implementation above.
unsafe impl Sync for NativeBytes {}

impl NativeBytes {
    pub const fn from_static(bytes: &'static [u8]) -> Self {
        Self {
            ptr: bytes.as_ptr(),
            len: bytes.len(),
        }
    }

    /// # Safety
    ///
    /// The pointer must remain valid for `len` bytes for the returned lifetime.
    pub unsafe fn as_slice<'a>(self) -> &'a [u8] {
        // SAFETY: The caller guarantees the descriptor storage is valid.
        unsafe { std::slice::from_raw_parts(self.ptr, self.len) }
    }
}

#[derive(Clone, Copy)]
#[repr(C)]
pub struct NativePluginDescriptorV1 {
    pub abi_version: u32,
    pub kind: u32,
    pub id: NativeBytes,
    pub version: NativeBytes,
    pub build_fingerprint: NativeBytes,
}

// SAFETY: Every pointer field follows the same immutable-static invariant as
// `NativeBytes`.
unsafe impl Send for NativePluginDescriptorV1 {}
// SAFETY: See the `Send` implementation above.
unsafe impl Sync for NativePluginDescriptorV1 {}

pub type PluginDescriptorFnV1 = unsafe extern "C" fn() -> *const NativePluginDescriptorV1;
pub type PluginOptionsSchemaFnV1 = unsafe fn() -> String;

#[cfg(feature = "agent")]
pub type AgentPluginCreateV15 =
    fn(&PluginLoadContext, &PluginOptionsValue) -> Result<Arc<dyn AgentPlugin>, PluginLoadError>;

#[cfg(feature = "provider")]
pub type ProviderPluginCreateV15 =
    fn(&PluginLoadContext, &PluginOptionsValue) -> Result<Arc<dyn ProviderPlugin>, PluginLoadError>;

#[cfg(feature = "session")]
pub type SessionPluginCreateV15 =
    fn(&PluginLoadContext, &PluginOptionsValue) -> Result<Arc<dyn SessionPlugin>, PluginLoadError>;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PluginScope {
    Global,
    Project { root: PathBuf },
    ExplicitPath,
}

#[derive(Debug, Clone)]
pub struct PluginLoadContext {
    cwd: PathBuf,
    package_dir: PathBuf,
    data_dir: PathBuf,
    cache_dir: PathBuf,
    scope: PluginScope,
    generation: u64,
}

impl PluginLoadContext {
    pub fn new(
        cwd: impl Into<PathBuf>,
        package_dir: impl Into<PathBuf>,
        data_dir: impl Into<PathBuf>,
        cache_dir: impl Into<PathBuf>,
        scope: PluginScope,
        generation: u64,
    ) -> Self {
        Self {
            cwd: cwd.into(),
            package_dir: package_dir.into(),
            data_dir: data_dir.into(),
            cache_dir: cache_dir.into(),
            scope,
            generation,
        }
    }

    pub fn cwd(&self) -> &Path {
        &self.cwd
    }

    pub fn package_dir(&self) -> &Path {
        &self.package_dir
    }

    pub fn data_dir(&self) -> &Path {
        &self.data_dir
    }

    pub fn cache_dir(&self) -> &Path {
        &self.cache_dir
    }

    pub fn scope(&self) -> &PluginScope {
        &self.scope
    }

    pub fn generation(&self) -> u64 {
        self.generation
    }

    #[doc(hidden)]
    pub fn for_generation(&self, generation: u64) -> Self {
        let mut context = self.clone();
        context.generation = generation;
        context
    }
}

pub trait NativePluginFactory: Sized + Send + Sync + 'static {
    type Options: DeserializeOwned + JsonSchema + Send + Sync + 'static;

    fn load(context: &PluginLoadContext, options: Self::Options) -> Result<Self, PluginLoadError>;
}

#[derive(Debug, thiserror::Error)]
pub enum PluginLoadError {
    #[error("invalid plugin options: {0}")]
    InvalidOptions(String),
    #[error("plugin initialization failed: {0}")]
    Initialization(String),
}

pub type PluginLoadResult<T> = Result<T, PluginLoadError>;

impl PluginLoadError {
    pub fn initialization(message: impl Into<String>) -> Self {
        Self::Initialization(message.into())
    }
}

pub fn decode_plugin_options<T: DeserializeOwned>(
    options: &PluginOptionsValue,
) -> Result<T, PluginLoadError> {
    serde_json::from_value(options.clone())
        .map_err(|error| PluginLoadError::InvalidOptions(error.to_string()))
}

pub fn ensure_empty_plugin_options(options: &PluginOptionsValue) -> Result<(), PluginLoadError> {
    if options.is_null() || options.as_object().is_some_and(serde_json::Map::is_empty) {
        Ok(())
    } else {
        Err(PluginLoadError::InvalidOptions(
            "this plugin does not accept options".to_string(),
        ))
    }
}

pub fn plugin_options_schema<T: JsonSchema>() -> String {
    serde_json::to_string(&schemars::schema_for!(T))
        .expect("a generated plugin options schema must serialize")
}

pub fn empty_plugin_options_schema() -> String {
    r#"{"type":"object","additionalProperties":false}"#.to_string()
}

#[cfg(feature = "agent")]
pub mod agent {
    pub mod prelude {
        pub use crate::{
            NativePluginFactory, PluginLoadContext, PluginLoadError, PluginLoadResult, agent,
        };
        pub use async_trait::async_trait;
        pub use pi_core::{
            AbortHandle, AbortSignal, AgentContext, AgentEndEvent, AgentHook, AgentHookInterests,
            AgentPlugin, AgentPluginContext, AgentStartEvent, AssistantMessage, AssistantStream,
            AssistantStreamId, BeforeAgentStartEvent, BeforeAgentStartPatch, Command,
            CommandContext, CommandError, CommandModelsContext, CommandOutcome,
            CommandSessionContext, CommandSpec, ContentBlock, ContentMetadata, ContextEvent,
            ContextPatch, ContextUsage, CustomMessageContent, CustomMessageInput,
            DirectCompletionRequest, EphemeralCompactionOptions, EphemeralSessionOutcome,
            EphemeralSessionRequest, EphemeralSessionStatus, ForkOptions, ForkPosition,
            InputContext, InputEvent, InputPatch, IsolatedSessionOptions, IsolatedSessionRequest,
            MessageDelivery, MessageEndEvent, MessageStartEvent, MessageUpdateEvent,
            ModelSelection, ModelsContext, NavigateTreeOptions, NewSessionOptions, NoticeLevel,
            PluginContextError, PluginContextResult, PluginError, PresentationMode,
            RegisterContext, ReplacedSessionContext, ResponseMetadataPatch, Result, RunId,
            ScopedModel, SendMessageOptions, SendUserMessageOptions, SessionContext,
            SessionEntryKind, SessionEntryView, SessionExecutionOrigin, SessionReplacement,
            SessionSnapshot, StreamEvent, ThinkingLevel, Tool, ToolCallEvent, ToolCallId,
            ToolCallPatch, ToolContext, ToolError, ToolExecutionEndEvent, ToolExecutionStartEvent,
            ToolExecutionUpdateEvent, ToolResult, ToolResultEvent, ToolResultPatch, ToolSpec,
            ToolUpdateSink, TurnEndEvent, TurnStartEvent, UiContext,
        };
        pub use serde_json::{Value, json};
    }
}

#[cfg(feature = "provider")]
pub mod provider {
    pub mod prelude {
        pub use crate::{
            NativePluginFactory, PluginLoadContext, PluginLoadError, PluginLoadResult, provider,
        };
        pub use async_trait::async_trait;
        pub use pi_core::{
            AbortHandle, AbortSignal, AfterProviderResponseEvent, BeforeProviderHeadersEvent,
            BeforeProviderRequestEvent, DirectCompletionRequest, EphemeralCompactionOptions,
            EphemeralSessionOutcome, EphemeralSessionRequest, EphemeralSessionStatus,
            IsolatedSessionOptions, IsolatedSessionRequest, ModelId, ModelSelection, ModelSpec,
            ModelsContext, PluginContextError, PluginContextResult, PluginError, PluginId,
            PresentationMode, Provider, ProviderCallContext, ProviderError, ProviderId,
            ProviderPlugin, ProviderPluginContext, ProviderRegisterContext, ProviderRequest,
            ProviderStream, Result, SessionContext, SessionEntryKind, SessionEntryView,
            SessionExecutionOrigin, SessionSnapshot, StreamEvent, ThinkingLevel, UiContext,
        };
        pub use serde_json::{Value, json};
    }
}

#[cfg(feature = "session")]
pub mod session {
    pub mod prelude {
        pub use crate::{
            NativePluginFactory, PluginLoadContext, PluginLoadError, PluginLoadResult, session,
        };
        pub use async_trait::async_trait;
        pub use pi_core::{
            AbortHandle, AbortSignal, CompactOptions, ContextUsage, DirectCompletionRequest,
            EphemeralCompactionOptions, EphemeralSessionOutcome, EphemeralSessionRequest,
            EphemeralSessionStatus, IsolatedSessionOptions, IsolatedSessionRequest, ModelSelection,
            ModelsContext, NoticeLevel, PluginContextError, PluginContextResult, PresentationMode,
            ScopedModel, SessionContext, SessionEntryKind, SessionEntryView,
            SessionExecutionOrigin, SessionSnapshot, ThinkingLevel, UiContext,
        };
        pub use pi_session::plugin::{
            SessionBeforeCompactEvent, SessionBeforeCompactResult, SessionBeforeForkEvent,
            SessionBeforeForkResult, SessionBeforeSwitchEvent, SessionBeforeSwitchResult,
            SessionBeforeTreeEvent, SessionBeforeTreeResult, SessionCompactEvent,
            SessionCompactFailedEvent, SessionInfoChangedEvent, SessionPlugin,
            SessionPluginContext, SessionPluginError, SessionShutdownEvent, SessionStartEvent,
            SessionTreeEvent,
        };
    }
}
