#![deny(unsafe_op_in_unsafe_fn)]

use std::sync::Arc;

use crate::{Plugin, ProviderPlugin};
use schemars::JsonSchema;
use serde::de::DeserializeOwned;
pub use serde_json::Value as PluginOptionsValue;

/// Version of the trusted Rust-ABI plugin contract.
///
/// ABI 24 moves native contracts into pi-plugin and consolidates host management.
/// ABI 23 shares PluginError and typed diagnostics across Agent and Session hooks.
/// ABI 22 unifies Agent and Session plugins and uses the shared prepare factory contract.
/// ABI 21 adds bounded recent-turn inheritance to isolated-session forks.
/// ABI 20 adds persistent isolated-session turns, messaging and follow-ups.
/// ABI 18 adds aggregate usage to managed isolated-session outcomes. ABI 17 adds
/// explicit fresh/fork initialization to isolated-session options.
/// ABI 16 adds detached provider usage/call accounting and the session usage
/// recording capability. ABI 15 replaces core tool-run state with a run identity and explicit
/// invocation-private Agent plugins for ephemeral Agents.
/// ABI 14 adds detached context compaction, transient execution provenance,
/// and typed invocation-local tool state. ABI 13 adds inherited fork prompts/history, invocation-local observations,
/// guarded dispatch, and input budgets. ABI 12 adds bounded ephemeral sessions to the generation-bound session
/// capability. ABI 11 adds tool-free direct completion to the generation-bound session
/// capability. ABI 10 adds inherited model, thinking, and active-tool selection for fresh
/// isolated sessions. ABI 9 added independently running sessions to the
/// generation-bound session context. ABI 8 added asynchronous semantic
/// confirmation to the UI context.
/// ABI 7 replaced cumulative message-update snapshots with a shared live stream
/// handle plus one compact [`pi_core::StreamEvent`] delta. ABI 6 shared immutable
/// cumulative partials; ABI 5 added the generation-bound Pi product context and
/// tool argument preparation.
/// Hosts must reject older artifacts before resolving their Rust-ABI
/// constructors.
pub const NATIVE_PLUGIN_ABI_VERSION: u32 = 24;
pub const BUILD_FINGERPRINT: &str = env!("PI_PLUGIN_BUILD_FINGERPRINT");

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u32)]
pub enum NativePluginKind {
    Plugin = 1,
    Provider = 2,
}

impl NativePluginKind {
    pub fn from_u32(value: u32) -> Option<Self> {
        match value {
            1 => Some(Self::Plugin),
            2 => Some(Self::Provider),
            _ => None,
        }
    }
}

#[derive(Clone, Copy)]
#[repr(C)]
pub struct NativeBytes {
    pub ptr: *const u8,
    pub len: usize,
}

// SAFETY: `NativeBytes` values in plugin descriptors only point at immutable
// static byte strings generated by the export macros.
unsafe impl Send for NativeBytes {}
// SAFETY: See the `Send` implementation above.
unsafe impl Sync for NativeBytes {}

impl NativeBytes {
    pub const fn from_static(bytes: &'static [u8]) -> Self {
        Self {
            ptr: bytes.as_ptr(),
            len: bytes.len(),
        }
    }

    /// # Safety
    ///
    /// The pointer must remain valid for `len` bytes for the returned lifetime.
    pub unsafe fn as_slice<'a>(self) -> &'a [u8] {
        // SAFETY: The caller guarantees the descriptor storage is valid.
        unsafe { std::slice::from_raw_parts(self.ptr, self.len) }
    }
}

#[derive(Clone, Copy)]
#[repr(C)]
pub struct NativePluginDescriptorV1 {
    pub abi_version: u32,
    pub kind: u32,
    pub id: NativeBytes,
    pub version: NativeBytes,
    pub build_fingerprint: NativeBytes,
}

// SAFETY: Every pointer field follows the same immutable-static invariant as
// `NativeBytes`.
unsafe impl Send for NativePluginDescriptorV1 {}
// SAFETY: See the `Send` implementation above.
unsafe impl Sync for NativePluginDescriptorV1 {}

pub type PluginDescriptorFnV1 = unsafe extern "C" fn() -> *const NativePluginDescriptorV1;
pub type PluginOptionsSchemaFnV1 = unsafe fn() -> String;

pub type PluginCreateV24 =
    fn(&PrepareContext, &PluginOptionsValue) -> Result<Option<Arc<dyn Plugin>>, PrepareError>;

pub type ProviderPluginCreateV24 = fn(
    &PrepareContext,
    &PluginOptionsValue,
) -> Result<Option<Arc<dyn ProviderPlugin>>, PrepareError>;

use crate::{PrepareContext, PrepareError};

pub fn decode_plugin_options<T: DeserializeOwned>(
    options: &PluginOptionsValue,
) -> Result<T, PrepareError> {
    serde_json::from_value(options.clone())
        .map_err(|error| PrepareError::InvalidOptions(error.to_string()))
}

pub fn ensure_empty_plugin_options(options: &PluginOptionsValue) -> Result<(), PrepareError> {
    if options.is_null() || options.as_object().is_some_and(serde_json::Map::is_empty) {
        Ok(())
    } else {
        Err(PrepareError::InvalidOptions(
            "this plugin does not accept options".to_string(),
        ))
    }
}

pub fn plugin_options_schema<T: JsonSchema>() -> String {
    serde_json::to_string(&schemars::schema_for!(T))
        .expect("a generated plugin options schema must serialize")
}

pub fn empty_plugin_options_schema() -> String {
    r#"{"type":"object","additionalProperties":false}"#.to_string()
}
